Use only stderr when returning the error for GetClusterOperatorStatus function
Currently, in case of failure the following return error string we get, which
really doesn't need to have the exit status in case of error.

```
error: stat /home/prkumar/.crc/machines/crc/kubeconfig: no such file or directory
 - exit status 1
```