Issue #226: Mark errors which are intentionally ignored
This silences
cmd/crc/cmd/config/config.go:53:12: Error return value of `cmd.Help` is not checked (errcheck)
			cmd.Help()
			        ^
cmd/crc/cmd/oc_env.go:62:26: Error return value of `executeOcTemplateStdout` is not checked (errcheck)
		executeOcTemplateStdout(shellCfg)
		                       ^
cmd/crc/cmd/console.go:59:17: Error return value of `browser.OpenURL` is not checked (errcheck)
	browser.OpenURL(result.URL)
	               ^
cmd/crc/cmd/root.go:23:11: Error return value of `cmd.Help` is not checked (errcheck)
		cmd.Help()
		        ^
cmd/crc/cmd/start.go:28:23: Error return value of `crcConfig.BindFlagSet` is not checked (errcheck)
	crcConfig.BindFlagSet(startCmd.Flags())
	                     ^
pkg/crc/errors/atexit.go:47:14: Error return value of `output.OutW` is not checked (errcheck)
		output.OutW(os.Stdout, fmt.Sprintf(text, args...))
		           ^
pkg/crc/preflight/preflight_checks_linux.go:320:9: Error return value of `cmd.Run` is not checked (errcheck)
	cmd.Run()
	       ^
pkg/crc/preflight/preflight_checks_linux.go:322:9: Error return value of `cmd.Run` is not checked (errcheck)
	cmd.Run()
	       ^
pkg/crc/services/dns/dns.go:42:33: Error return value of `drivers.RunSSHCommandFromDriver` is not checked (errcheck)
	drivers.RunSSHCommandFromDriver(serviceConfig.Driver, "sudo podman rm -f dnsmasq")
	                               ^
pkg/crc/services/dns/dns.go:47:33: Error return value of `drivers.RunSSHCommandFromDriver` is not checked (errcheck)
	drivers.RunSSHCommandFromDriver(serviceConfig.Driver, fmt.Sprintf("sudo rm -f /var/lib/cni/networks/podman/%s", dnsContainerIP))
	                               ^
pkg/crc/systemd/host.go:45:16: Error return value of `c.DaemonReload` is not checked (errcheck)
	c.DaemonReload()
	              ^
pkg/crc/systemd/host.go:55:16: Error return value of `c.DaemonReload` is not checked (errcheck)
	c.DaemonReload()
	              ^
pkg/crc/systemd/host.go:65:16: Error return value of `c.DaemonReload` is not checked (errcheck)
	c.DaemonReload()
	              ^

https://github.com/code-ready/crc/issues/226