Openshift CI: Switch to centos-stream base image
Current image is causing issue on the CI.

```
 ---> Running in 0ecead35430d
CentOS Linux 8 - AppStream                      108  B/s |  38  B     00:00
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
The command '/bin/sh -c yum install -y libvirt-devel curl git gcc make golang diffutils' returned a non-zero code: 1
make: *** [Makefile:22: crc-driver-libvirt-centos8] Error 1
```

This patch update it to `quay.io/centos/centos:stream8` which
doesn't seem to have this issue.