Issue #226: Add missing error checks/propagation
This fixes:
cmd/crc/cmd/root.go:39:18: Error return value of `config.InitViper` is not checked (errcheck)
	config.InitViper()
	                ^
pkg/crc/config/viper_config.go:61:16: Error return value of `f.WriteString` is not checked (errcheck)
		f.WriteString("{}")
		             ^
pkg/extract/extract.go:106:15: Error return value of `os.MkdirAll` is not checked (errcheck)
			os.MkdirAll(path, file.Mode())
			           ^
pkg/crc/machine/machine.go:178:29: Error return value of `addNameServerToInstance` is not checked (errcheck)
		if addNameServerToInstance(host.Driver, startConfig.NameServer); err != nil {
		                          ^
pkg/crc/network/template.go:23:11: Error return value of `t.Execute` is not checked (errcheck)
	t.Execute(&resolvFile, values)
	         ^
pkg/crc/preflight/preflight_checks_common.go:47:10: Error return value of `w.Write` is not checked (errcheck)
		w.Write(data)
		       ^
pkg/crc/services/dns/template.go:73:11: Error return value of `t.Execute` is not checked (errcheck)
	t.Execute(&dnsConfigFile, values)
	         ^
pkg/crc/state/global.go:71:16: Error return value of `json.Unmarshal` is not checked (errcheck)
	json.Unmarshal(raw, &cfg)
	              ^

https://github.com/code-ready/crc/issues/226