Issue #337 Add resource as parameter for waitForOpenshiftAPIServer function
As of now we are just using `oc get pods` to check if apiserver is running.
What actually happen non-core resource take some time and it might fails something like below.

```
error: the server doesn't have a resource type "proxy"
```