Podman: Use podman system connection setting to add ssh connection
As of now user have to do `eval $(crc podman-env)` to export podman
connection specific environment variable to current shell session.
Podman cli have `system connection` command which manage the ssh
destination information for podman configuration which consumed
by podman client.

With this PR now if a user have podman-remote client binary to path
then after `crc start` they can directly use podman commands without
executing current `eval` command. `podman-env` command option still
there to support backward compatibility and also exposing moby specific
environment variable. It will still make sense if user don't have podman
remote binary in the path.

```
✗ ./crc start
[...]
  $ eval $(crc podman-env)
  $ podman COMMAND

✗ podman system connection ls
Name                         URI                                                         Identity                                    Default
crc                          ssh://core@127.0.0.1:2222/run/user/1000/podman/podman.sock  /Users/prkumar/.crc/machines/crc/id_ecdsa   true
crc-root                     ssh://core@127.0.0.1:2222/run/podman/podman.sock            /Users/prkumar/.crc/machines/crc/id_ecdsa   false

✗ podman info
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:

x  ./crc stop
INFO Stopping the instance, this may take a few minutes...
Stopped the instance

x podman info
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: Connection to bastion host (ssh://core@127.0.0.1:2222/run/user/1000/podman/podman.sock) failed.: ssh: handshake failed: read tcp 127.0.0.1:64934->127.0.0.1:2222: read: connection reset by peer
```