Issue #3514 Remove crc instance entries from known_hosts file
while using the podman preset in CRC the instance identity is added to the
known_hosts file and when it changes podman-remote complains about it  and
shows the following error:
```
Error: failed to connect: ssh: handshake failed: knownhosts: key mismatch
```

this will occur in crc when users upgrade podman from 4.3.1 to 4.4.1 with this patch it'll
remove the [127.0.0.1]:2222 entries from known_hosts which should work-around this issue