Make mock-nss.sh executeable
In the openshift CI the container fails because it see mock-nss.sh
doesn't have permission to execute so fixing the permission.

```
/bin/bash: line 8: /bin/mock-nss.sh: Permission denied
error: failed to execute wrapped command: exit status 1
```