preflight: Fix tests with go 1.21
If `check` is an anonymous functions, comparisons do not necessarily
work well, and this broke with go 1.21:

=== RUN   TestCountPreflights
    preflight_linux_test.go:508:
                Error Trace:    /home/anjan/Work/github.com/code-ready/main/pkg/crc/preflight/preflight_linux_test.go:508
                                                        /home/anjan/Work/github.com/code-ready/main/pkg/crc/preflight/preflight_linux_test.go:528
                                                        /home/anjan/Work/github.com/code-ready/main/pkg/crc/preflight/preflight_linux_test.go:540
                Error:          Not equal:
                                expected: 0x2659080
                                actual  : 0x2672120
                Test:           TestCountPreflights
                Messages:       github.com/crc-org/crc/v2/pkg/crc/preflight.bundleCheck.checkBundleExtracted.func1 != github.com/crc-org/crc/v2/pkg/crc/preflight.init.checkBundleExtracted.func2

This commit changes this to compare configKeySuffix instead.

This fixes https://github.com/crc-org/crc/issues/4030

Signed-off-by: Christophe Fergeau <cfergeau@redhat.com>