[openshift-ci] Fix the gcloud-sdk version to 365.0.1
Looks like latest version 366.0.0 have issue with libffi and causing
following error in the CI
```
$ gcloud auth activate-service-account --quiet --key-file gce.json
ERROR: gcloud crashed (SystemError): ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)

If you would like to report this issue, please run the following command:
  gcloud feedback
```