images: Update golang base image
There is no version of registry.access.redhat.com/ubi8/go-toolset with
golang 1.20:
```
$ podman build -f ./images/build-e2e/Dockerfile .
[1/2] STEP 1/5: FROM registry.access.redhat.com/ubi8/go-toolset:1.20 AS builder
Trying to pull registry.access.redhat.com/ubi8/go-toolset:1.20...
Error: creating build container: initializing source docker://registry.access.redhat.com/ubi8/go-toolset:1.20: reading manifest 1.20 in registry.access.redhat.com/ubi8/go-toolset: manifest unknown
```

This commit switches to
registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.20-openshift-4.15
which has golang 1.20 and is usable without authentication.
This stays on a rhel8 image as some of the test nodes are still using
rhel8, and building on a rhel9 node, and trying to run on a rhel8 node
is not possible (some libc linking issues at startup).

The builds will be noisy until
https://github.com/openshift-eng/art-tools/pull/115 is merged and gets
into these images.
If needed, we can set GO_COMPLIANCE_INFO=0 in the images environment to
make the build more quiet.